runtime: python310
service: qr-code-generator
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_instances: 1
env_variables:
  FLASK_ENV: "production"
entrypoint: gunicorn src.app:app --workers 1 --threads 8 --timeout 0
